// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.region.update.updated", 1691988747);
user_pref("browser.search.region", "KR");
user_pref("calendar.caldav.googleResync", 1691988745);
user_pref("calendar.list.sortOrder", "828a86bd-62f4-4d70-b8a8-0887927c320c");
user_pref("calendar.registry.828a86bd-62f4-4d70-b8a8-0887927c320c.calendar-main-default", true);
user_pref("calendar.registry.828a86bd-62f4-4d70-b8a8-0887927c320c.calendar-main-in-composite", true);
user_pref("calendar.registry.828a86bd-62f4-4d70-b8a8-0887927c320c.disabled", true);
user_pref("calendar.registry.828a86bd-62f4-4d70-b8a8-0887927c320c.name", "Home");
user_pref("calendar.registry.828a86bd-62f4-4d70-b8a8-0887927c320c.type", "storage");
user_pref("calendar.registry.828a86bd-62f4-4d70-b8a8-0887927c320c.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "Asia/Seoul");
user_pref("calendar.ui.version", 3);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 1);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1692245846179");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1692245837);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20230704155023");
user_pref("extensions.lastAppVersion", "102.13.0");
user_pref("extensions.lastPlatformVersion", "102.13.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"4febba0f-8058-418d-9263-1d2974d71c49\",\"google@search.mozilla.org\":\"46ff5102-d021-4d7f-8123-7762952aebba\",\"ddg@search.mozilla.org\":\"9eb854c1-b40e-4714-b2e8-78bf14811084\",\"amazondotcom@search.mozilla.org\":\"f5071395-dea7-4f42-b410-114530188274\",\"wikipedia@search.mozilla.org\":\"a4c34b66-95a2-4e2a-b99f-295a7c91e248\",\"bing@search.mozilla.org\":\"ea6dc191-379b-4e86-b192-fb6562ffd82b\"}");
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.ui-rdf.version", 34);
user_pref("mailnews.database.global.datastore.id", "5ca2cc2c-08ef-44e9-be49-422788fcf38");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "102.13.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("toolkit.telemetry.cachedClientID", "ea013d42-fbcc-4a13-a2b8-6c0ced5a7a27");
user_pref("toolkit.telemetry.previousBuildID", "20230704155023");
